double getDriveFL();
double getDriveTL();
double getDriveBL();
double getDriveFR();
double getDriveTR();
double getDriveBR();
double getDriveL();
double getDriveR();
double getDrive();
void driveReset();
double getHeatFL();
double getHeatTL();
double getHeatBL();
double getHeatFR();
double getHeatTR();
double getHeatBR();
void setDriveFL(double speed);
void setDriveTL(double speed);
void setDriveBL(double speed);
void setDriveFR(double speed);
void setDriveTR(double speed);
void setDriveBR(double speed);
void setDriveFull(double flSpeed, double tlSpeed, double blSpeed, double frSpeed, double trSpeed, double brSpeed);
void setDrive(double lSpeed, double rSpeed);
void driveBrake();
void driveCoast();
void goTime(double lSpeed, double rSpeed, double timeValue);
void goP(int dir, double speed, double dist, double pStop, double maxError);
void turnEncoder(int dir, double speed, double dist);
double getInertialYaw();
void calibrateInertial();
void resetAngle();
void turnInertial(int dir, double speed, double dist, double pStop, double maxError);
int turnP(int dir, double initSpeed, double speed, double dist, double speedStart, double speedCut, double slowFactor, bool smooth);